### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by panvakalo** [seatsio/seatsio-vue#74]
Hi there.

I'm trying to make the language of the chart reactive, based on the current language of my app, but even if the language attribute of the `SeatsioSeatingChart` changes, the language of chart stays the same as the one when it got first rendered.

I tried also to rerender the chart with the language change, but still after rerendering the chart's language persists.

Is there a more proper way to do this?

**Comment by mortendevold** [comment]
Hi,

Well this is certainly a case of better late than never :smile:. This issue has gone under our radar, but you are indeed right that the component doesn't react to prop changes. We have however addressed this in our most recent release, version `3.7.0`. Please give it a try and let us know if you run into any issues. Thanks for bringing this to our attention!
