### ISSUE TITLE
Add 'main' attribute to package.json

### ISSUE THREAD

**Issue by mattkdigitickets** [seatsio/seatsio-vue#80]
When we use this package in a vue3 project the project builds fine through vite however the vitest suite fails with

> Error: Failed to resolve entry for package "@seatsio/seatsio-vue". The package may have incorrect main/module/exports specified in its package.json.

A bunch of debugging suggests this is because the `package.json` that ships in `@seatsio/seatsio-vue` doesn't contain a `main` parameter.

Manually adding
> "main": "dist/seatsio-vue.js",

to `@seatsio/seatsio-vue/package.json` resolves this issue and allows the test suite to run as normal.

Is it possible for you to publish an update to this package with the main parameter included?

**Comment by mroloux** [comment]
Good point 👍 That's been fixed in https://github.com/seatsio/seatsio-vue/releases/tag/v3.6.0
